#!/usr/bin/php
<?php
namespace Ytmusicapi;

include __DIR__ . "/../vendor/autoload.php";
include "polyfills.php";
include "helpers.php";
include "constants.php";
include "auth/models.php";
include "auth/exceptions.php";
include "auth/credentials.php";
include "auth/token.php";
include "auth/types.php";
include "auth/browser.php";

// php vendor/bin/setup-ytmusicapi oauth --file oauth.json
// php vendor/bin/setup-ytmusicapi browser --file browser.json

/**
 * Requests browser headers from the user via command line and returns a string that can be passed to YTMusic()
 *
 * @param string $filepath Optional filepath to store headers to.
 * @param string $headers_raw Optional request headers copied from browser. Otherwise requested from terminal
 * @return string configuration headers string
 */
function setup($filepath = null, $headers_raw = null) {
	return setup_browser($filepath, $headers_raw);
}

/**
 * Starts oauth flow from the terminal and returns a string that can be passed to YTMusic()
 *
 * @param string $filepath Optional filepath to store headers to.
 * @param Session $session Session to use for authentication
 * @param array $proxies Proxies to use for authentication
 * @param bool (Not implemented) $open_browser – If True, open the default browser with the setup link
 * @param string $client_id Optional. Used to specify the client_id oauth should use for authentication
 *   flow. If provided, client_secret MUST also be passed or both will be ignored.
 * @param string $client_secret Optional. Same as client_id but for the oauth client secret.
 */
function setup_oauth(
	$filepath = null,
	$session = null,
	$proxies = null,
	$open_browser = false,
	$client_id = null,
	$client_secret = null
) {
	if ($client_id && $client_secret) {
		$oauth_credentials = new OAuthCredentials($client_id, $client_secret, $session, $proxies);
	} else {
		$oauth_credentials = new OAuthCredentials(null, null, $session, $proxies);
	}

	RefreshingToken::prompt_for_token($oauth_credentials, $open_browser, $filepath);
}

function show_help() {
	echo "Usage: php bin/vendor/setup.php <setup_type> [--file <filename>]\n\n";
	echo "setup_type: oauth, browser\n\n";
	exit;
}

function parse_args() {
	global $argv;

	if (count($argv) <= 1) {
		show_help();
	}

	$setup_type = strtolower($argv[1]);
	if ($setup_type !== "oauth" && $setup_type !== "browser") {
		show_help();
	}

	if (!isset($argv[2]) || strtolower($argv[2]) !== "--file") {
		$filename = $setup_type . ".json";
	} else {
		$filename = isset($argv[3]) ? $argv[3] : $setup_type . ".json";
	}

	return (object)[
		"setup_type" => $setup_type,
		"file" => $filename
	];
}


function main() {
	$args = parse_args();

	$filename = $args->file;

	echo "Creating {$filename} with your authentication credentials...\n";
	if ($args->setup_type === "oauth") {
		setup_oauth($filename, false);
	} else {
		setup($filename);
	}
	echo "Created $filename.\n";
}
main();
